In [1]:
import nltk


showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

Installed these for part 1 and 2:
- pip install scipy    
- pip install python_speech_features
- pip install hmmlearn 
- pip install pathlib      
- pip install nltk  
- pip install gensim 
- pip install pattern
- pip install SpeechRecognition 
- pip install pyaudio  

In [1]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import make_multilabel_classification
# This produces a feature matrix of token counts, similar to what
# CountVectorizer would produce on text.
X, _ = make_multilabel_classification(random_state=0)
lda = LatentDirichletAllocation(n_components=5,
    random_state=0)
lda.fit(X)

# get topics for some given samples:
lda.transform(X[-2:])

array([[0.00360392, 0.25499205, 0.0036211 , 0.64236448, 0.09541846],
       [0.15297572, 0.00362644, 0.44412786, 0.39568399, 0.003586  ]])

In [3]:
import numpy as np
print(X)
print(np.array(X).shape)

[[3. 1. 4. ... 4. 1. 3.]
 [5. 0. 6. ... 0. 0. 3.]
 [3. 4. 1. ... 3. 2. 5.]
 ...
 [2. 1. 2. ... 1. 0. 3.]
 [6. 4. 1. ... 1. 3. 5.]
 [2. 4. 2. ... 5. 4. 2.]]
(100, 20)
