In [13]:
import numpy as np
from nltk.tokenize import sent_tokenize, word_tokenize, WordPunctTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer, LancasterStemmer, SnowballStemmer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import make_multilabel_classification

In [2]:
input_text = []
count = 0
for line in open('data.txt', 'r').read().split('\n'):
    count += 1
    if line != '':
        input_text.append(line)

In [3]:
word_dict = {}
punctuation_dict = {}
for index, line in enumerate(input_text):
    word_dict[index] = word_tokenize(line)
    punctuation_dict[index] = WordPunctTokenizer().tokenize(line)

In [16]:
lemma_word_dict = {}
for line in word_dict:
    lemma_word_dict[line] = []
    lemmatizer = WordNetLemmatizer()
    for i in word_dict[line]:
        lemma_word_dict[line].append(lemmatizer.lemmatize(i, pos='n'))

In [18]:
stem_word_dict = {}
for line in word_dict:
    stem_word_dict[line] = []
    for i in word_dict[line]:
        stem_word_dict[line].append(SnowballStemmer('english').stem(i))

In [21]:
num = 2
bow = {}
for i in range(2):
    for w in stem_word_dict[i]:
        if w not in bow:
            bow[w] = 0

In [27]:
bow_dict = {}
for line in word_dict:
    bow_dict[line] = bow.copy()

In [33]:
for w in stem_word_dict:
    for ww in stem_word_dict[w]:
        if ww in bow_dict[w]:
            bow_dict[w][ww] += 1

In [ ]:
X = []
for w in bow_dict:


In [26]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import make_multilabel_classification
# This produces a feature matrix of token counts, similar to what
# CountVectorizer would produce on text.
X, _ = make_multilabel_classification(random_state=0)
lda = LatentDirichletAllocation(n_components=5,
    random_state=0)
lda.fit(X)
print(X)
print(X[-2:])
# get topics for some given samples:
lda.transform(X[-2:])

[[3. 1. 4. ... 4. 1. 3.]
 [5. 0. 6. ... 0. 0. 3.]
 [3. 4. 1. ... 3. 2. 5.]
 ...
 [2. 1. 2. ... 1. 0. 3.]
 [6. 4. 1. ... 1. 3. 5.]
 [2. 4. 2. ... 5. 4. 2.]]
[[6. 4. 1. 4. 4. 3. 2. 1. 1. 2. 2. 3. 3. 4. 5. 0. 2. 1. 3. 5.]
 [2. 4. 2. 3. 4. 1. 5. 2. 3. 6. 4. 0. 2. 2. 0. 3. 2. 5. 4. 2.]]


array([[0.00360392, 0.25499205, 0.0036211 , 0.64236448, 0.09541846],
       [0.15297572, 0.00362644, 0.44412786, 0.39568399, 0.003586  ]])